config/routes.rb
Pixtr::Application.routes.draw do
  get "/galleries/random" => "random_galleries#show"

  root "homes#show"

  resource :dashboard, only: [:show]

  resources :galleries do
    member do 
      post "like" => "gallery_likes#create"
      delete "unlike" => "gallery_likes#destroy"
    end
    resources :images, only: [:new, :create]
  end

  resources :charges, only: [:new, :create]

  get 'tags/:tag', to: 'images#index', as: :tag

  get '/search', to: 'searches#index'

  resources :groups, only: [:index, :new, :create, :show] do
    member do
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
    member do
      post "like" => "group_likes#create"
      delete "unlike" => "group_likes#destroy"
    end
  end

  resources :comments, only: [:destroy]

  resources :images, except: [:index, :new, :create] do
    resources :comments, only: [:create]
    member do
      post "like" => "image_likes#create"
      delete "unlike" => "image_likes#destroy"
    end
  end

  resources :users, only: [:show] do
    member do
      post "/follow" => "following_relationships#create"
      delete "/unfollow" => "following_relationships#destroy"
    end

    collection do
      get "/following" => "following_relationships#index"
      get "/followers" => "following_relationships#index"
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_memberships, dependent: :destroy
  has_many :members, through: :group_memberships
  has_many :group_images, dependent: :destroy
  has_many :images, through: :group_images
  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authorize, except: [:show]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      current_user.join @group
      redirect_to @group
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @images = @group.images.includes(gallery: [:user])
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/views/groups/_join_group_button.html.erb
<div id="membership_button_form">
  <% if !current_user.member? group %>
    <%= button_to "Join Group", join_group_path(group), remote: true %>
  <% else %>
    <%= button_to "Leave Group", leave_group_path(group), method: :delete, remote: true %>
  <% end %>
</div>

app/views/groups/_like_button.html.erb
<div id="like_button_form">
  <% if current_user.like? @group %>
    <%= button_to "Unlike this Group", unlike_group_path, method: :delete, remote: true %>
  <% else %>
    <%= button_to "Like this Group", like_group_path, remote: true %>
  <% end %>
</div>

app/views/groups/index.html.erb
<%= link_to "Add a Group", new_group_path %>

<ul>
  <% @groups.each do |group| %>
    <li><%= link_to group.name, group %></li>
  <% end %>
</ul>

app/views/groups/new.html.erb
<%= form_for @group do |form| %>
  <%= render "form_errors", target: @group %>
  <%= form.text_field :name, placeholder: "Name" %>
  <%= form.text_area :description, placeholder: "Description" %>
  <%= form.submit "Create Group" %>
<% end %>

app/views/groups/show.html.erb
<h2><%= @group.name %></h2>

<%= render "like_button", group: @group %>

<% if signed_in? %>
  <%= render "join_group_button", group: @group %>
<% end %>

<p>	
<%= render @images %>
</p>