config/routes.rb
Pixtr::Application.routes.draw do
  get "/galleries/random" => "random_galleries#show"

  root "homes#show"

  resource :dashboard, only: [:show]

  resources :galleries do
    member do 
      post "like" => "gallery_likes#create"
      delete "unlike" => "gallery_likes#destroy"
    end
    resources :images, only: [:new, :create]
  end

  resources :charges, only: [:new, :create]

  get 'tags/:tag', to: 'images#index', as: :tag

  get '/search', to: 'searches#index'

  resources :groups, only: [:index, :new, :create, :show] do
    member do
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
    member do
      post "like" => "group_likes#create"
      delete "unlike" => "group_likes#destroy"
    end
  end

  resources :comments, only: [:destroy]

  resources :images, except: [:index, :new, :create] do
    resources :comments, only: [:create]
    member do
      post "like" => "image_likes#create"
      delete "unlike" => "image_likes#destroy"
    end
  end

  resources :users, only: [:show] do
    member do
      post "/follow" => "following_relationships#create"
      delete "/unfollow" => "following_relationships#destroy"
    end

    collection do
      get "/following" => "following_relationships#index"
      get "/followers" => "following_relationships#index"
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy
  has_many :group_images, dependent: :destroy
  has_many :groups, through: :group_images
  validates :name, presence: true
  validates :description, presence: true
  validates :url, presence: true
  acts_as_taggable

  def user
    gallery.user
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    if params[:tag]
      @images = Image.tagged_with(params[:tag])
    else
      @images = Image.all
    end
  end

  def show
    @image = Image.find(params[:id])
    @comment = Comment.new
    @comments = @image.comments.includes(:user).recent.page(params[:page]).per(2)
    @tags = @image.tags
  end

  def new
    @gallery = current_user.galleries.find(params[:gallery_id])
    @image = Image.new
  end

  def create
    @gallery = current_user.galleries.find(params[:gallery_id])
    @image = @gallery.images.new(image_params)
    if @image.save
      redirect_to @gallery
    else
      render :new
    end
  end

  def edit
    @image = current_user.images.find(params[:id])
    @groups = current_user.groups
  end

  def update
    @image = current_user.images.find(params[:id])
    if @image.update(image_params)
      redirect_to @image
    else
      @groups = current_user.groups
      render :edit
    end
  end

  def destroy
    image = current_user.images.find(params[:id])
    image.destroy
    redirect_to image.gallery
  end

  private

  def image_params
    params.require(:image).permit(
      :name,
      :description,
      :url,
      :tag_list,
      group_ids: []
    )
  end
end

app/views/images/_image.html.erb
<%= link_to image_tag(image.url, width: 500), image %>
By: <%= link_to image.user.email, image.user %>

<h2><%= link_to image.name, image %></h2>

<p><%= image.description %></p>

app/views/images/edit.html.erb
<%= link_to "<<back", gallery_path(@image.gallery_id) %>

<h1><%= @image.name %></h1>

<img src="<%= @image.url %>">

<p><%= @image.description %></p>

<%= form_for([@image]) do |form| %>
  <%= render "form_errors", target: @image %>
  <%= form.text_field :name, placeholder: "Name" %>
  <%= form.text_area :description, placeholder: "Description" %>
  <%= form.text_field :url, placeholder: "URL" %>
  <%= form.text_field :tag_list, placeholder: "Tags (separated by commas)" %>
  <div>
    <%= form.collection_check_boxes :group_ids, @groups, :id, :name %>
  </div>
  <%= form.submit "Update Image" %>
<% end %>

app/views/images/index.html.erb
<%= render @images %>

app/views/images/new.html.erb
<body class="form-background">
  <div class="form">
    <%= form_for([@gallery, @image]) do |form| %>
      <% if @image.errors.any? %>
        <%= render "form_errors", target: @image %>
      <% end %>
      <%= form.text_field :name, placeholder: "Name" %>
      <%= form.text_field :description, placeholder: "Description" %>
      <%= form.text_field :url, placeholder: "URL" %>
      <div class="form-button">
        <%= form.submit "Add Image" %>
      </div>
    <% end %>
  </div>
</body>

app/views/images/show.html.erb
<%= link_to "<<back", gallery_path(@image.gallery_id) %>

<h1><%= @image.name %></h1>

<%= image_tag(@image.url, width: 400) %>

Tags: <%= raw @image.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>

<div id="like_image_form">
  <p><%= pluralize(@image.likes.count, "like") %></p>
  <% if current_user.like? @image %>
    <%= button_to "Unlike", unlike_image_path, method: :delete, remote: true %>
  <% else %>
    <%= button_to "Like", like_image_path, remote: true %>
  <% end %>
</div>

<p><%= @image.description %></p>
<p>Added by: <%= link_to @image.user.email, @image.user %></p>
<p>Added on: <%= @image.created_at.to_date %></p>

<div>
  <% if @image.user == current_user %>
    <%= link_to "Edit This Image", edit_image_path(@image) %>
    <%= link_to "Delete image", @image, method: :delete, confirm: "Are you sure?" %>	
  <% end %>
</div>

<div>
  <% if signed_in? %>
    <div id="comment_form">
      <%= form_for([@image, @comment], remote: true) do |form| %>
        <%= form.text_area :body, size: "55x5" %>
        <%= form.submit "Comment" %>
      <% end %>
    </div>
  <% else %>	
    <%= link to "Sign In", sign_in_path %> to comment.
  <% end %>	
</div>

<div id="comments_displayed">
  <%= render @comments %>
</div>

<div id= "paginate">
  <%= paginate @comments %>
</div>